[env]
build_dir = "build"
source_dir = "src"
SESSION_NAME = "builder"
NODE_ENV = "development"
AppName = "Writer_"
Author = "Zero"

[tasks.build]
run = """
#!/bin/bash

tmux has-session -t "$SESSION_NAME" 2>/dev/null

if [ $? -eq 0 ]; then
    echo "Session '$SESSION_NAME' already exists. Attaching to it."
    tmux attach-session -t "$SESSION_NAME"
else
    echo "Creating new session '$SESSION_NAME' and running commands."
    tmux new-session -d -s "$SESSION_NAME"
    tmux split-window -v -t "$SESSION_NAME"
    tmux split-window -v -t "$SESSION_NAME.0"
    tmux split-window -h -t "$SESSION_NAME.0"
    tmux send-keys -t "$SESSION_NAME.0" "mise run builder" ENTER
    tmux send-keys -t "$SESSION_NAME.1" "mise run server" ENTER
    tmux send-keys -t "$SESSION_NAME.2" "mise run livereload" ENTER
    tmux send-keys -t "$SESSION_NAME.3" "jj" ENTER
    tmux attach-session -t "$SESSION_NAME"
fi
"""

[tasks.builder]
run = "nodemon builder.mjs"

[tasks.server]
run = "python3 -m http.server --directory build 8001"

[tasks.livereload]
run = "livereload build"
