[env]
build_dir = "public"
source_dir = "src"
SESSION_NAME = "builder"
AppName = "Writeros"
domain = "writeros.app"
Author = "Zero"
NODE_ENV = "development"

[tasks.build]
run = "node builder.mjs"

[tasks.server]
run = "python3 -m http.server --directory build 8001"

[tasks.stop]
run = "tmux kill-session -t $SESSION_NAME"

[tasks.dev]
run = """
#!/bin/bash

tmux has-session -t "$SESSION_NAME" 2>/dev/null

if [ $? -eq 0 ]; then
    echo "Session '$SESSION_NAME' already exists. Attaching to it."
    tmux attach-session -t "$SESSION_NAME"
else
    echo "Creating new session '$SESSION_NAME' and running commands."
    tmux new-session -d -s "$SESSION_NAME"
    tmux split-window -v -t "$SESSION_NAME"
    tmux send-keys -t "$SESSION_NAME.0" "mise run build" ENTER
    tmux send-keys -t "$SESSION_NAME.1" "jj" ENTER
    tmux select-pane -t "$SESSION_NAME.1"
    tmux attach-session -t "$SESSION_NAME"
fi
"""

[tasks.deploy]
run = """
#!/bin/bash
if jj log -r '@ & empty()' --limit 1 --no-graph >/dev/null; then
  echo "Current commit is empty."
else
  jj new
fi
npm version patch --no-git-tag-version
jj describe -m "Deploying version $(node -p "require('./package.json').version")"
jj new
jj mm @-
jj git push
"""
