name: Deploy to docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run builder
        run: |
          export BUILD_DIR="${{ secrets.BUILD_DIR }}"
          export SOURCE_DIR="${{ secrets.SOURCE_DIR }}"
          export APP_NAME="${{ secrets.APP_NAME }}"
          export AUTHOR="${{ secrets.AUTHOR }}"

          # Persist for subsequent steps
          echo "BUILD_DIR=${BUILD_DIR}" >> $GITHUB_ENV
          echo "SOURCE_DIR=${SOURCE_DIR}" >> $GITHUB_ENV
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV
          echo "AUTHOR=${AUTHOR}" >> $GITHUB_ENV
          node ./builder.mjs

      - name: Deploy to docs branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.BUILD_DIR }}
          publish_branch: docs
          commit_message: 'Deploy site to docs branch'
